COUNTRIES = [
    "Sweden",
    "Ukraine",
    "Germany",
    "Luxembourg",
    "Netherlands",
    "Israel",
    "Lithuania",
    "Spain",
    "Estonia",
    "Ireland",
    "Latvia",
    "Greece",
    "United Kingdom",
    "Norway",
    "Italy",
    "Serbia",
    "Finland",
    "Portugal",
    "Armenia",
    "Cyprus",
    "Switzerland",
    "Slovenia",
    "Croatia",
    "Georgia",
    "France",
    "Austria",
]
